DROP TABLE IF EXISTS patient CASCADE;
DROP TABLE IF EXISTS doctor CASCADE;
DROP TABLE IF EXISTS available_date CASCADE;
DROP TABLE IF EXISTS visit CASCADE;
DROP TABLE IF EXISTS patient_history CASCADE;